openapi: 3.0.0
info:
  title: School API
  version: 1.0.0
  description: >
    School API poskytuje data o školách v ČR, včetně adres, oborů, kapacit a kontaktních údajů. Je vhodné pro mapové aplikace, vyhledávače škol, statistiky a školní projekty.

servers:
  - url: https://rybovka23.sps-prosek.cz/Weby/api_endpoint
    description: Produkční server

paths:
  /info.php:
    get:
      summary: Vrátí základní informace o API a databázi
      description: >
        Endpoint vrací základní informace o API a stavu připojení k databázi.
      responses:
        '200':
          description: Úspěšná odpověď
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                    description: Status odpovědi
                  data:
                    type: object
                    description: JSON objekt s daty
                    properties:
                      name:
                        type: string
                        description: Jméno API
                      api_author:
                        type: string
                        description: Autor API
                      api_version:
                        type: string
                        description: Verze API
                      docs:
                        type: string
                        description: Odkaz na dokumentaci
                      supported_formats:
                        type: array
                        description: Pole podporovaných formátů
                        items:
                          type: string
                      utc_time:
                        type: string
                        format: date-time
                        description: Čas na serveru
                      db_info:
                        type: object
                        description: JSON objekt s informacemi o databázi
                        properties:
                          connected:
                            type: boolean
                            description: Stav připojení k databázi
                          db_time:
                            type: string
                            nullable: true
                            description: Čas databáze. Může být null, pokud db není připojena
                          db_version:
                            type: string
                            nullable: true
                            description: Verze databáze. Může být null, pokud db není připojena
                          error:
                            type: string
                            nullable: true
                            description: Výpis erroru pokud selže připojení k databázi. Může být null, pokud je db připojena.
                      server_info:
                        type: string
                        description: Informace o serveru - funkce php_uname()
                      php_version:
                        type: string
                        description: Verze PHP
              examples:
                ok:
                  value:
                    status: 200
                    data:
                      name: "School API"
                      api_author: "rybovka"
                      api_version: "1.0.0"
                      docs: "https://s-api.gitbook.io/s_api"
                      supported_formats:
                        - "json"
                      utc_time: "2026-02-02T18:24:50Z"
                      db_info:
                        connected: true
                        db_time: "2026-02-02 19:26:18"
                        db_version: "5.5.68-MariaDB"
                      server_info: "Linux public 5.14.0-611.16.1.el9_7.x86_64"
                      php_version: "8.5.1"
                db_down:
                  value:
                    status: 200
                    data:
                      name: "School API"
                      api_author: "rybovka"
                      api_version: "1.0.0"
                      docs: "https://s-api.gitbook.io/s_api"
                      supported_formats:
                        - "json"
                      utc_time: "2026-02-02T18:24:50Z"
                      db_info:
                        connected: false
                        error: "chybova hlaska"
                      server_info: "Linux public 5.14.0-611.16.1.el9_7.x86_64"
                      php_version: "8.5.1"

        '400':
          description: Chybná metoda. Nutno použít GET
          content:
            application/json:
              example:
                status: 400
                error: "nespravna metoda, pouzijte GET"
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    description: Status odpovědi
                  error:
                    type: string
                    description: Chybová hláška
