openapi: 3.0.0
info:
  title: School API
  version: 1.0.0
  description: >
    API pro školní projekt – poskytuje informace o serveru, databázi a dalších funkcích.
    Endpoint vždy vrací status 200, i pokud databáze není připojena. Informace o připojení
    je uvedena v poli db_info->connected.

servers:
  - url: https://rybovka23.sps-prosek.cz/Weby/api_endpoint
    description: Produkční server

paths:
  /info.php:
    get:
      summary: Vrátí základní informace o API a databázi
      description: >
        Endpoint vrací základní informace o API a stavu připojení k databázi.
      responses:
        '200':
          description: Úspěšná odpověď
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  data:
                    type: object
                    properties:
                      name:
                        type: string
                      api_author:
                        type: string
                      api_version:
                        type: string
                      docs:
                        type: string
                      supported_formats:
                        type: array
                        items:
                          type: string
                      utc_time:
                        type: string
                        format: date-time
                      db_info:
                        type: object
                        properties:
                          connected:
                            type: boolean
                          db_time:
                            type: string
                            nullable: true
                          db_version:
                            type: string
                            nullable: true
                      server_info:
                        type: string
                      php_version:
                        type: string
              example:
                status: 200
                data:
                  name: "School API"
                  api_author: "rybovka"
                  api_version: "1.0.0"
                  docs: "https://s-api.gitbook.io/s_api"
                  supported_formats:
                    - "json"
                  utc_time: "2026-02-02T18:24:50Z"
                  db_info:
                    connected: true
                    db_time: "2026-02-02 19:26:18"
                    db_version: "5.5.68-MariaDB"
                  server_info: "Linux public 5.14.0-611.16.1.el9_7.x86_64"
                  php_version: "8.5.1"

        '400':
          description: Chybná metoda. Nutno použít GET
          content:
            application/json:
              example:
                status: 400
                error: "nespravna metoda, pouzijte GET"
